server:
    port: 11009
spring:
    application:
        name: microservice-zipkin-client
    zipkin:
        base-url: http://localhost:9411
        discovery-client-enabled: false
        sender:
            type: web
    sleuth:
        sampler:
            probability: 1.0
            percentage: 1
        web:
            client:
                enabled: true  
management:
  endpoints:
    web:
      exposure:
        # 开放所有监控端点
        include: '*'
  endpoint:
    health:
      # 是否展示健康检查详情
      show-details: always